#!/bin/bash

# radio online dial
# autor : nodos
# fecha : 06-09-2014
# licencia : GPL


# LISTA DE RADIOS
# separa el identificador de la url con una barra vertical |
l=(
  'radiomadre|http://200.68.81.65:8000/am530'
  'unasound|http://vacapiloto.comunidadhuayra.org:8000/unasound'
  'unasound-mp3|http://vacapiloto.comunidadhuayra.org:8000/unasound.mp3'
  'kasandrxs|http://stream.codigosur.org:8000/kasandrxs.mp3'
  'cajradioacevedo|http://vacapiloto.comunidadhuayra.org:8000/cajradioacevedo.mp3'
  'fmtinkunaco|http://stream.codigosur.org:8000/fm-tinkunaco.mp3'
  'radiomerlina|http://tuxmerlin.with-linux.com:8000/listen'
  'radionacional|http://radionacional.alsolnet.com:8270/sc_rad1'
  'radialistas|http://stream.codigosur.org:8000/radialistas.mp3'
  'radiomoreno|http://stream.codigosur.org:8000/fmmoreno.mp3'
  'yaxhilradio|http://radio.flujos.org:8000/yaxhilradio.oga'
  'radiopatriatecnopolis|http://67.212.166.178:7728/;'
  'fm_105_3_del_carmen_tu_comunitaria_punta_de_manga_uruguay|http://radios-online.info:2930'
  'fm_89_3_radio_gráfica_bs_as|http://70.38.87.45:8000/radiografica.ogg'
  'fm_91_9__conexion_maturin_venezuela|http://radio.comunaactiva.org.ve:8000/conexionfm.mp3'
  'fm_95_1_radio_bolivariana_monogas_venezuela|http://radio.comunaactiva.org.ve:8000/bolivariana951.mp3'
  'fm_la_nueva_98_1_formosa|http://200.58.118.108:8184/stream'
  'la_radio_popular|http://190.104.213.202:8000/stream/1/'
  'lounge_radio|http://yp.shoutcast.com/sbin/tunein-station.pls?id=1288934'
  'vtv_canal_8|http://radio.comunaactiva.org.ve:8000/vtv.mp3'
  'entrebyte-ve|http://190.202.87.180:9800/airtime_128|entrebyte.com.ve'
  'radiofutura|http://streamingargentino4.com.ar:7288/;stream.nsv'
)


# ELECCIÓN DE REPRODUCTOR
# puede ser vlc, mplayer, avplay, firefox, ...
r='vlc '
r='mplayer '
r='mplayer -cache 400 -cache-min 50 '


# FUNCIÓN DE AYUDA
function ayuda {
  sep='-----------------------------------------'
  echo 'RADIO ONLINE DIAL'
  echo $sep
  echo 'se usa así:'
  echo '  '$(which $0)' ID-EMISORA'
  echo 
  echo 'lista de emisoras:'
  echo -e "  ID-EMISORA\t\t\tURL"
  for a in ${l[@]}
  do
    i=$(echo  $a | cut -d'|' -f1)
    u=$(echo  $a | cut -d'|' -f2)
    echo -e '  '$i"\t\t"$u
  done
  echo
  echo 'para agregar nuevas emisoras, editar este documento'
  echo 'y agregarlas en la sección "lista de radios"'
  echo $sep
}

# MUESTRA AYUDA
if [ "" == "$1" ]; then ayuda; exit; fi

# REPRODUCE
for a in ${l[@]}
do
  i=$(echo  $a | cut -d'|' -f1)
  u=$(echo  $a | cut -d'|' -f2)
  if [ "$i" == "$1" ]
  then
    echo '----------------------------------'
    echo $1
    echo '----------------------------------'
    echo $u
    echo '----------------------------------'
    $r $u
    exit
  fi
done

# ERROR
ayuda
echo ':( radio NO ENCONTRADA !'
exit
