#!/bin/bash

# selector-de-flujos
# autor : nodos-dsnn.com.ar
# fecha : 06-09-2014
# licencia : GPL 3


# DATOS DE APLICACIÓN
titApp='SELECTOR DE FLUJOS'
nomApp='selector-de-flujos'
sep='-----------------------------------------'


# LISTA DE RADIOS
archivoLista='flujos.lista'
l=$(cat $archivoLista)


# ELECCIÓN DE REPRODUCTOR
# puede ser vlc, mplayer, avplay, firefox, ...
r='vlc '
r='mplayer '
r='mplayer -cache 400 -cache-min 50 '


# FUNCIONES
function ayuda {
  echo $sep
  echo $titApp
  echo $sep
  echo 'se usa así:'
  echo '   '$nomApp' [ID-FLUJO]'
  echo 
  echo 'Para ver la lista de flujos disponibles:'
  echo '   '$nomApp' -l'
  echo 
  echo 'Para agregar o modificar flujos,'
  echo 'editar el archivo "flujos.lista" .'
  echo 'Los elementos de cada item van separados'
  echo 'por "|" (barra vertical). Y cada en una'
  echo 'línea diferente.'
  echo
  echo
}

function verLista {
  echo $sep
  echo $titApp
  echo $sep
  echo 'Lista de flujos disponibles:'
  echo -e "  ID-FLUJO\t\t\t\tURL"
  for a in ${l[@]}
  do
    i=$(echo  $a | cut -d'|' -f1)
    u=$(echo  $a | cut -d'|' -f2)
    echo -e '  '$i"\t\t"$u
  done
  echo
  echo
}


# SELECCIÓN DE OPCIONES DE ACCIÓN
if [ "" == "$1" ]; then ayuda; exit; fi
if [ "-h" == "$1" ]; then ayuda; exit; fi
if [ "-l" == "$1" ]; then verLista; exit; fi

# REPRODUCE
for a in ${l[@]}
do
  i=$(echo  $a | cut -d'|' -f1)
  u=$(echo  $a | cut -d'|' -f2)
  if [ "$i" == "$1" ]
  then
    echo $sep
    echo $titApp' >> '$1
    echo '  << '$u
    echo $sep
    $r $u
    exit
  fi
done

# ERROR
ayuda
echo ':( flujo NO ENCONTRADO !'
exit
